2008-11-10 03:35 UTC+0100 Viktor Szakats (harbour.01 syenar hu)   * source/vm/fm.c     ! Fixed missing abort() on WinCE. (for Pelles C only, but       the fix should work for any WinCE compilers).     ; TOFIX: Now the only remaining showstopper for PellesC5 WinCE              support is:              ../../math.c(652): error #3120: [asm] Symbol 'inf' is undefined.
git-svn-id: http://harbour-project.svn.sourceforge.net/svnroot/harbour-project@9893 ef52b332-12a4-b543-bf59-08b57769829b