2009-10-01 17:58 UTC+0200 Viktor Szakats (harbour.01 syenar.hu)   * INSTALL   * utils/hbmk2/hbmk2.prg   * config/os2/gcc.mk   + config/os2/gccomf.mk     + Added OS/2 GCC OMF support.       This tries to fix resource support in hbmk2 compared to David's       solution. hbmk2 support is completely newly done, .mk support was imported       as is, with little change in actication logic.     ! Fixed to use $(ECHOQUOTE) in some $(ECHO) command parameters.     ; NOTE: Until we don't add autodetection for OMF supporting GCC versions,             it will have to be selected manually using HB_COMPILER=gccomf.             Notice that for GCC 4.x this is obligatory since COFF support is             broken in these versions.             Additional EMX* envvar options are left as an excercise for the             users, I intentionally didn't document these in INSTALL, as INSTALL             servers as Harbour documentation, not 3rd party tools like GCC.
  * config/global.mk
    ! Minor in comment.

  * contrib/hbqt/Makefile
  * contrib/hbqt/hbqts/Makefile
  * contrib/gtqtc/gtqtcs/Makefile
  * contrib/gtqtc/Makefile
    ! Disabled QT dependent parts for msvcia64 targets.
    ; Fails with error:
      ---
      z:\devl\qt\4.5.2\include\qtcore\../../src/corelib/tools/qvector.h(541) : warning C4346: 'QVector<T>::iterator' : dependent name is not a type
              prefix with 'typename' to indicate a type
      z:\devl\qt\4.5.2\include\qtcore\../../src/corelib/tools/qvector.h(541) : error C2143: syntax error : missing ';' before 'QVector<T>::insert'
      z:\devl\qt\4.5.2\include\qtcore\../../src/corelib/tools/qvector.h(541) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
      z:\devl\qt\4.5.2\include\qtcore\../../src/corelib/tools/qvector.h(541) : fatal error C1903: unable to recover from previous error(s); stopping compilation
      ---

  * package/winuni/HARBOUR_README_MINGWARM
    * Minor raw update to document newly found --force-local tar switch.



git-svn-id: http://harbour-project.svn.sourceforge.net/svnroot/harbour-project@12634 ef52b332-12a4-b543-bf59-08b57769829b