2009-03-18 01:04 UTC+0100 Viktor Szakats (harbour.01 syenar hu)   * include/hbatomic.h     ! Typo (__inline__ -> __inline).     ! Temply disabled new _MSC_VER inline asm code, because it causes this with POCC5:       include\hbatomic.h(268): error #3114: [asm] Invalid combination of opcode and operands.       include\hbatomic.h(273): error #3114: [asm] Invalid combination of opcode and operands.
git-svn-id: http://harbour-project.svn.sourceforge.net/svnroot/harbour-project@10638 ef52b332-12a4-b543-bf59-08b57769829b