2008-11-10 02:14 UTC+0100 Viktor Szakats (harbour.01 syenar hu)   * config/w32/poccce.cf     + Added -D_WINCE to C compiler options.
  * source/pp/hbpp.c
  * source/main/harbour.c
    ! Reenabled hbwmain.c for __POCC__.

  * source/pp/hbpp.c
    * WinCE cleanup. (__MINGW32CE__ is always defined 
      when HB_WINCE is, so checking for HB_WINCE seems enough)
    % Removed #include <windows.h>.
    ; Please verify me.

  ; TOFIX: Pelles C 5.0 WinCE build results so far:

--- ERRORS
POLINK: error: Unresolved external symbol 'RegOpenKeyExA'.
POLINK: fatal error: 1 unresolved external(s).
../../harbour.c(56): fatal error #1035: Can't find include file "hbverbld.h".
../../math.c(652): error #3120: [asm] Symbol 'inf' is undefined.
../../cmdarg.c(61): fatal error #1035: Can't find include file "hbverbld.h".
POLINK: fatal error: File not found: 'hbvm.lib'.
contrib\gtwvg\gtwvg.h(78): fatal error #1035: Can't find include file <olectl.h>.
../../ctmath2.c(324): error #3120: [asm] Symbol 'inf' is undefined.
../../winapi.c(70): error #2048: Undeclared identifier 'CS_OWNDC'.
../../winapi.c(75): error #2048: Undeclared identifier 'IDI_APPLICATION'.
../../winapi.c(75): error #2140: Type error in argument 2 to 'LoadIconA'; found 'int', expected 'const char *'.
../../winapi.c(181): error #2048: Undeclared identifier 'MFS_DISABLED'.
../../getenvrn.c(177): error #2168: Operands of = have incompatible types 'char *' and 'int'.
../../odbc.c(94): fatal error #1035: Can't find include file <sql.h>.
contrib\hbsqlit3\sqlite3\sqlite3.c(9936): error #2168: Operands of = have incompatible types '(incomplete) struct tm *' and 'int'.
contrib\hbsqlit3\sqlite3\sqlite3.c(9937): error #2152: Unknown field 'tm_year' of '(incomplete) struct tm'.
contrib\hbsqlit3\sqlite3\sqlite3.c(9938): error #2152: Unknown field 'tm_mon' of '(incomplete) struct tm'.
contrib\hbsqlit3\sqlite3\sqlite3.c(9939): error #2152: Unknown field 'tm_mday' of '(incomplete) struct tm'.
contrib\hbsqlit3\sqlite3\sqlite3.c(9940): error #2152: Unknown field 'tm_hour' of '(incomplete) struct tm'.
contrib\hbsqlit3\sqlite3\sqlite3.c(9941): error #2152: Unknown field 'tm_min' of '(incomplete) struct tm'.
contrib\hbsqlit3\sqlite3\sqlite3.c(9942): error #2152: Unknown field 'tm_sec' of '(incomplete) struct tm'.
contrib\hbsqlit3\sqlite3\sqlite3.c(22136): error #2120: Redeclaration of 'localtime' previously declared at contrib\hbsqlit3\sqlite3\sqlite3.c(9936): found '(incomplete) struct tm * __cdecl function(const unsigned long int *)', expected 'int __cdecl function()'.
contrib\hbsqlit3\sqlite3\sqlite3.c(22137): error #2149: Undefined size for 'y' with type '(incomplete) struct tm'.
contrib\hbsqlit3\sqlite3\sqlite3.c(22137): error #2149: Undefined size for 'y' with type '(incomplete) struct tm'.
contrib\hbsqlit3\sqlite3\sqlite3.c(22147): error #2152: Unknown field 'tm_year' of '(incomplete) struct tm'.
contrib\hbsqlit3\sqlite3\sqlite3.c(22148): error #2152: Unknown field 'tm_mon' of '(incomplete) struct tm'.
contrib\hbsqlit3\sqlite3\sqlite3.c(22149): error #2152: Unknown field 'tm_wday' of '(incomplete) struct tm'.
contrib\hbsqlit3\sqlite3\sqlite3.c(22150): error #2152: Unknown field 'tm_mday' of '(incomplete) struct tm'.
contrib\hbsqlit3\sqlite3\sqlite3.c(22151): error #2152: Unknown field 'tm_hour' of '(incomplete) struct tm'.
contrib\hbsqlit3\sqlite3\sqlite3.c(22152): error #2152: Unknown field 'tm_min' of '(incomplete) struct tm'.
contrib\hbsqlit3\sqlite3\sqlite3.c(22153): error #2152: Unknown field 'tm_sec' of '(incomplete) struct tm'.
../../win_ole.c(77): fatal error #1035: Can't find include file <olectl.h>.
../../wincorec.c(150): error #2048: Undeclared identifier 'WS_MAXIMIZE'.
../../wincorec.c(166): error #2168: Operands of = have incompatible types 'HWND' and 'int'.
../../hbsyslog.c(31): error #2140: Type error in argument 2 to 'RegisterEventSourceW'; found 'const char *', expected 'const wchar_t *'.
../../hbsyslog.c(97): error #2140: Type error in argument 8 to 'ReportEventW'; found 'const char * *', expected 'const wchar_t * *'.
C:\devl\allegro-4.2.2\include\allegro\platform\almsvc.h(23): fatal error #1035: Can't find include file <malloc.h>.
../../firebird.c(456): error #2149: Undefined size for 'times' with type '(incomplete) struct tm'.
../../firebird.c(487): error #2152: Unknown field 'tm_year' of '(incomplete) struct tm'.
../../firebird.c(488): error #2152: Unknown field 'tm_mon' of '(incomplete) struct tm'.
../../firebird.c(489): error #2152: Unknown field 'tm_mday' of '(incomplete) struct tm'.
../../firebird.c(490): error #2152: Unknown field 'tm_hour' of '(incomplete) struct tm'.
../../firebird.c(491): error #2152: Unknown field 'tm_min' of '(incomplete) struct tm'.
../../firebird.c(492): error #2152: Unknown field 'tm_sec' of '(incomplete) struct tm'.
../../firebird.c(501): error #2152: Unknown field 'tm_year' of '(incomplete) struct tm'.
../../firebird.c(501): error #2152: Unknown field 'tm_mon' of '(incomplete) struct tm'.
../../firebird.c(501): error #2152: Unknown field 'tm_mday' of '(incomplete) struct tm'.
../../firebird.c(510): error #2152: Unknown field 'tm_hour' of '(incomplete) struct tm'.
../../firebird.c(511): error #2152: Unknown field 'tm_min' of '(incomplete) struct tm'.
../../firebird.c(512): error #2152: Unknown field 'tm_sec' of '(incomplete) struct tm'.
../../fi_winfu.c(98): error #2048: Undeclared identifier 'CBM_INIT'.
../../fi_winfu.c(99): error #2168: Operands of = have incompatible types 'HBITMAP' and 'int'.
C:\devl\mysql-5.0.67\include\mysql_com.h(183): error #2001: Syntax error: expected '}' but found 'SOCKET'.
C:\devl\mysql-5.0.67\include\mysql_com.h(222): error #2156: Unrecognized declaration.
C:\devl\mysql-5.0.67\include\mysql_com.h(335): error #2001: [ LOTS MORE ]

--- WARNINGS
../../winapi.c(194): warning #2027: Missing prototype for 'InsertMenuItem'.
../../winapi.c(219): warning #2027: Missing prototype for 'SetMenu'.
../../getenvrn.c(177): warning #2027: Missing prototype for 'GetEnvironmentStrings'.
../../getenvrn.c(246): warning #2027: Missing prototype for 'FreeEnvironmentStrings'.
contrib\hbsqlit3\sqlite3\sqlite3.c(9936): warning #2027: Missing prototype for 'localtime'.
../../tpwin32.c(75): warning #2027: Missing prototype for 'BuildCommDCB'.
../../wincorec.c(164): warning #2027: Missing prototype for 'CreateMDIWindow'.
C:\devl\PellesC-501\include\wince\ws2tcpip.h(381): warning #2115: Local 'dwMsgLen' is initialized but never used.
C:\devl\PellesC-501\include\wince\ws2tcpip.h(392): warning #2115: Local 'dwMsgLen' is initialized but never used.
../../fi_winfu.c(97): warning #2027: Missing prototype for 'CreateDIBitmap'.
../../fi_winfu.c(147): warning #2027: Missing prototype for 'GetDIBits'.
C:\devl\mysql-5.0.67\include\mysql_com.h(222): warning #2099: Missing type specifier.
C:\devl\mysql-5.0.67\include\mysql.h(275): error #2011: Declared parameter 'warning_count' is missing.
../../sqlbase.c(509): warning #2130: Result of unsigned comparison is constant.


git-svn-id: http://harbour-project.svn.sourceforge.net/svnroot/harbour-project@9890 ef52b332-12a4-b543-bf59-08b57769829b