; Merging all remaining last-minute fixes to 1.0 from main branch.
2008-08-13 16:35 UTC+0200 Viktor Szakats (harbour.01 syenar hu)
   * doc/whatsnew.txt
     * More minor adjustments.

2008-08-13 15:30 UTC+0200 Przemyslaw Czerpak (druzus/at/priv.onet.pl)
  * harbour/config/hpux/gcc.cf
  * harbour/config/sunos/gcc.cf
    ! fixed typo in comment

  * harbour/config/dos/owatcom.cf
    ! fixed build process in POSIX SHELL environment

2008-08-13 13:55 UTC+0200 Viktor Szakats (harbour.01 syenar hu)
   * doc/whatsnew.txt
     * Minor adjustments, typo fixes.

2008-08-13 05:50 UTC+0200 Przemyslaw Czerpak (druzus/at/priv.onet.pl)
  * harbour/contrib/gtwvg/gtwvg.h
    ! added missing defines for DMC builds

  * harbour/contrib/gtwvg/wvgutils.c
    ! use HB_PTRDIFF for pointer to number casting

2008-08-13 05:30 UTC+0200 Przemyslaw Czerpak (druzus/at/priv.onet.pl)
  * harbour/source/pp/ppcore.c
  * harbour/source/pp/hbpp.c
  * harbour/source/vm/itemapi.c
  * harbour/source/vm/hvm.c
  * harbour/source/common/hbver.c
  * harbour/source/macro/macrolex.c
  * harbour/source/hbpcre/pcrecomp.c
  * harbour/source/compiler/hbpcode.c
  * harbour/contrib/hbmisc/spd.c
  * harbour/contrib/hbsqlit3/sqlite3/sqlite3.c
    * pacified warnings

  * harbour/config/w32/dm.cf
    * updated to work with SHELL env
    - comment -w7 switch

2008-08-13 04:16 UTC+0200 Viktor Szakats (harbour.01 syenar hu)
   * contrib/hbodbc/odbc.c
     ! Some recently updated code now conditionally restored 
       to pre-ODBC 3.0 versions to support compilers (namely 
       __DMC__) with old ODBC headers. I couldn't find out 
       how to point DMC to newer (SDK) ODBC headers, but as 
       soon as we do, we can remove this workaround.
       There is a similar problem with MSVC6.

2008-08-13 03:08 UTC+0200 Viktor Szakats (harbour.01 syenar hu)
   * source/rtl/gtwvt/gtwvt.c
     ! Fixed one possible minor bug (synced from gtwvg.c), 
       when pressing the mouse button for mark&select.

   * contrib/hbodbc/odbc.c
     ! Fixed some compile errors for __DMC__.
     ; TOFIX: Some more remain.
       ../../odbc.c(517) : Error: undefined identifier 'SQL_IS_INTEGER'
       ../../odbc.c(525) : Error: undefined identifier 'SQLSetStmtAttr'
       ../../odbc.c(536) : Error: undefined identifier 'SQLGetConnectAttr'
       ../../odbc.c(549) : Error: undefined identifier 'SQLGetStmtAttr'

   * contrib/gtwvg/gtwvg.c
   * contrib/gtwvg/gtwvg.h
   * contrib/gtwvg/wvgcore.c
   * contrib/gtwvg/wvgutils.c
     ! Synced (to some extent) with gtwvt.c, so that it now 
       also compiles with __DMC__.
     ! Fixed a some more compile errors for __DMC__.
     ; TOFIX: Some more remain.
       ../../wvgutils.c(356) : Error: undefined identifier 'TTM_SETMARGIN'
       ../../wvgutils.c(367) : Error: undefined identifier 'TTM_GETMAXTIPWIDTH'
       ../../wvgutils.c(371) : Error: undefined identifier 'TTM_SETMAXTIPWIDTH'
       ../../wvgutils.c(385) : Error: undefined identifier 'TTM_GETTIPBKCOLOR'
       ../../wvgutils.c(389) : Error: undefined identifier 'TTM_SETTIPBKCOLOR'
       ../../wvgutils.c(402) : Error: undefined identifier 'TTM_GETTIPTEXTCOLOR'
       ../../wvgutils.c(406) : Error: undefined identifier 'TTM_SETTIPTEXTCOLOR'
       ../../wvgutils.c(761) : Error: undefined identifier 'UINT_PTR'
       ../../wvgutils.c(1296) : Error: undefined identifier 'LONG_PTR'
       ../../wvgutils.c(1297) : Error: undefined identifier 'ul'

   * config/w32/dm.cf
     ! Fix missed from previous commit added.
     * Added -x C compiler switch.

2008-08-13 03:24 UTC+0200 Przemyslaw Czerpak (druzus/at/priv.onet.pl)
  * harbour/source/rtl/gtwvt/gtwvt.c
    ! use HB_PTRDIFF for handle to number casting

2008-08-13 02:30 UTC+0200 Viktor Szakats (harbour.01 syenar hu)
   * make_b32.bat
   * make_b32.mak
     - Removed dummy option HB_BUILD_MODE.

2008-08-13 01:11 UTC+0200 Viktor Szakats (harbour.01 syenar hu)
   * doc/whatsnew.txt
     * Extended releases notes/issues section.

   * config/w32/dm.cf
     ! Fixed to exclude "possible extraneous ';'" warnings 
       for every for()/while()/etc constructs with an empty body.
     ! Further fixes to link/lib rules.
     ; TOFIX1: odbc.c, gtwvg.c still don't compile.
     ; TOFIX2: Harbour executables won't run, by simply doing nothing.

   * source/rtl/gtwvt/gtwvt.c
     ! Fixed to compile with __DMC__.
     ; NOTE: Przemek, could you please check these?

   * include/hbsetup.h
     ! snprintf() for __DMC__.
     
   * contrib/hbw32/dllcall.c
     ! Fixed casting for __DMC__.

   * contrib/hbsqlit3/hbsqlit3.c
     ! Workaround for Pelles C 4.5 and Open Watcom, so that 
       sqlite3.c won't be included for these compilers.
       Pelles C 4.5 crashes, Open Watcom 1.7 goes into an 
       infinite loop on this huge file. For thes compilers 
       the sqlite3 library should be supplied by the users.

   * contrib/hbapollo/apollo.c
     ! Fixed to compile with Open Watcom.

   * source/vm/mainwin.c
   * source/vm/hvm.c
     ! Fix for __DMC__ startup problem:
       'OPTLINK : Warning 134: No Start Address'

2008-08-12 22:49 UTC+0200 Przemyslaw Czerpak (druzus/at/priv.onet.pl)
  * harbour/config/w32/dm.cf
    * updated for central library directory used by Harbour - not tested

  * harbour/config/w32/xcc.cf
    ! fixed include PATH in XCC builds - Viktor be carefull with
      cleaning -I<path> parameter. Some compilers use different
      rulles then the one you may expect using the most popular
      ones and such operation will break compilation. F.e. XCC
      seems to ignore source file location for releative paths
      so in GNU make builds it's necessary to add "-I$(TOP)"
      instead of "-I." and when included file starts with ".."
      then it does not try to use it with paths set by -I option
      so we need -I$(TOP)$(ROOT) and hard coded for this compiler
      directories in include/hbregex.h and include/hbzip.h

  * harbour/source/hbzlib/zutil.h
    ! do not use fdopen() with XCC - it does not support it

  * harbour/contrib/examples/pp/pp.c
  * harbour/contrib/examples/pp/hbppcore.c
  * harbour/source/common/hbfsapi.c
  * harbour/source/rtl/fnsplit.c
  * harbour/source/rtl/fstemp.c
    ! always use _POSIX_PATH_MAX + 1 buffers

  * harbour/source/compiler/gencobj.c
    * extended line buffer size

  * harbour/source/rtl/gtcrs/gtcrs.h
    * removed unnecessary declaration for _POSIX_PATH_MAX
      it's always defined in Harbour header files

  * harbour/source/rtl/inkey.c
  * harbour/source/rtl/hbinet.c
  * harbour/source/rtl/gtwvt/gtwvt.c
    * use hb_array[SG]et*() functions insteaf of
      hb_item*( hb_arrayGetItemPtr, ... )

2008-08-12 20:55 UTC+0200 Viktor Szakats (harbour.01 syenar hu)
   + config/w32/dm.cf
     + Digital Mars .cf file added. Some cleanups done, and 
       TOFIX added besides the following:
     ; TOFIX: This file comes from xhb, and it needs to be updated 
              to create core and contrib .lib files in central dir.
              Until then it doesn't work. Ryszard, if you see 
              this, could you take a look?

   * config/dos/djgpp.cf
   * config/w32/bcc32.cf
   * config/w32/xcc.cf
     % Unnecessary CPPFLAGS -I options deleted:
       -I$(TOP)
       -I$(TOP)include
       -Iinclude
       -I$(TOP)$(ROOT)

   ; NOTE/TODO: CPPFLAGS -i usage should be cleaned for these files:
     config/dos/owatcom.cf
     config/linux/owatcom.cf
     config/os2/gcc.cf
     config/w32/owatcom.cf
     config/w32/watcom.cf

2008-08-11 21:20 UTC+0200 Viktor Szakats (harbour.01 syenar hu)
   * config/hpux/gcc.cf
   * config/linux/gcc.cf
   * config/os2/gcc.cf
   * config/bsd/gcc.cf
     ! Never force the platform from the make files, rather 
       rely on the autodetection in hbsetup.h.
       Compiling default parts of the software should only rely 
       on manually set macros if there is no reasonable chance to 
       make the detection automatic.

   * contrib/rddado/Makefile
     ! Excluded from OS/2 builds.

2008-08-11 18:24 UTC+0200 Viktor Szakats (harbour.01 syenar hu)
   * config/rules.cf
     % Removed unnecessary -I option from Harbour command line.

   * ChangeLog
     + Added entry to signal the branching.


git-svn-id: http://harbour-project.svn.sourceforge.net/svnroot/harbour-project@9175 ef52b332-12a4-b543-bf59-08b57769829b