2010-01-25 12:35 UTC+0100 Przemyslaw Czerpak (druzus/at/priv.onet.pl)   * harbour/contrib/hbwin/win_misc.c     ! fixed buffer overflow in WIN_WIDETOANSI() caused by wrongly calculated       buffer size
  * harbour/utils/hbmk2/hbmk2.prg
    * updated names of xHarbour libraries - now it works in static mode
      TOFIX: -xhb shared mode uses 'harbour' instead of 'xharbour' library
              and 'hbmainstd' instead of 'mainstd'
      TOFIX2: -gui switch in -xhb mode cause compile time error:
                  /tmp/hbmk_auhl2d.c:8: error: syntax error before "void"


git-svn-id: http://harbour-project.svn.sourceforge.net/svnroot/harbour-project@13704 ef52b332-12a4-b543-bf59-08b57769829b