2009-07-03 09:35 UTC+0200 Viktor Szakats (harbour.01 syenar.hu)   * include/hbdefs.h     ! hbUChar, hbSChar fixed to not depend on legacy types.
  * utils/hbmk2/hbmk2.hu_HU.po
  * utils/hbmk2/hbmk2.prg
  * utils/hbmk2/Makefile
    + Enabled -mt switch on DOS platform.
    + Enabled MT builds on DOS platform.
      (currently its used by -jobs switch, maybe internal
      Harbour compiling can use this feature)

  * contrib/hbmysql/mysql.c
  * contrib/hbct/ctstrfil.c
  * contrib/hbct/print.c
  * contrib/xhb/hbxml.c
  * contrib/xhb/dbf2txt.c
  * contrib/xhb/filestat.c
  * contrib/hbsqlit3/hbsqlit3.c
  * contrib/hbnf/fttext.c
  * contrib/hbnf/dispc.c
  * contrib/hbcurl/hbcurl.c
  * contrib/hbgd/gdwrp.c
  * contrib/hbmisc/hb_f.c
  * contrib/hbtip/utils.c
  * source/vm/memvars.c
  * source/vm/set.c
  * source/rtl/console.c
  * source/rtl/philes.c
  * source/rtl/gttrm/gttrm.c
  * source/rtl/memofile.c
  * source/rdd/dbsql.c
  * source/rdd/dbffpt/dbffpt1.c
  * examples/pp/pp.c
    % FS API call cast cleanups.
      (removed explicit casts for the most part, added const in few
      places, changed some BYTE types to char.)
    * Formatting.

  * source/vm/task.c
    ! Minor text sync in debug calls.

  ; TOFIX:
    ../../filesys.c(1698) : error C2065: 'Flags' : undeclared identifier
    ../../filesys.c(1792) : error C2065: 'Flags' : undeclared identifier



git-svn-id: http://harbour-project.svn.sourceforge.net/svnroot/harbour-project@11615 ef52b332-12a4-b543-bf59-08b57769829b